using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace RosClientLib
{
    public class Mavros
    {
        public enum NavFrame : uint
        {
            FRAME_GLOBAL = 0u,
            FRAME_LOCAL_NED = 1u,
            FRAME_MISSION = 2u,
            FRAME_GLOBAL_REL_ALT = 3u,
            FRAME_LOCAL_ENU = 4u,
        };

        public enum Command : uint
        {
            AIRFRAME_CONFIGURATION = 2520u,
            ARM_AUTHORIZATION_REQUEST = 3001u,
            COMPONENT_ARM_DISARM = 400u,
            CONDITION_DELAY = 112u,
            CONDITION_CHANGE_ALT = 113u,
            CONDITION_DISTANCE = 114u,
            CONDITION_YAW = 115u,
            CONDITION_LAST = 159u,
            CONDITION_GATE = 4501u,
            CONTROL_HIGH_LATENCY = 2600u,
            DO_FOLLOW = 32u,
            DO_FOLLOW_REPOSITION = 33u,
            DO_SET_MODE = 176u,
            DO_JUMP = 177u,
            DO_CHANGE_SPEED = 178u,
            DO_SET_HOME = 179u,
            DO_SET_PARAMETER = 180u,
            DO_SET_RELAY = 181u,
            DO_REPEAT_RELAY = 182u,
            DO_SET_SERVO = 183u,
            DO_REPEAT_SERVO = 184u,
            DO_FLIGHTTERMINATION = 185u,
            DO_CHANGE_ALTITUDE = 186u,
            DO_LAND_START = 189u,
            DO_RALLY_LAND = 190u,
            DO_GO_AROUND = 191u,
            DO_REPOSITION = 192u,
            DO_PAUSE_CONTINUE = 193u,
            DO_SET_REVERSE = 194u,
            DO_SET_ROI_LOCATION = 195u,
            DO_SET_ROI_WPNEXT_OFFSET = 196u,
            DO_SET_ROI_NONE = 197u,
            DO_CONTROL_VIDEO = 200u,
            DO_MOUNT_CONFIGURE = 204u,
            DO_MOUNT_CONTROL = 205u,
            DO_SET_CAM_TRIGG_DIST = 206u,
            DO_FENCE_ENABLE = 207u,
            DO_PARACHUTE = 208u,
            DO_MOTOR_TEST = 209u,
            DO_INVERTED_FLIGHT = 210u,
            DO_SET_CAM_TRIGG_INTERVAL = 214u,
            DO_MOUNT_CONTROL_QUAT = 220u,
            DO_GUIDED_MASTER = 221u,
            DO_GUIDED_LIMITS = 222u,
            DO_ENGINE_CONTROL = 223u,
            DO_LAST = 240u,
            DO_TRIGGER_CONTROL = 2003u,
            DO_VTOL_TRANSITION = 3000u,
            GET_HOME_POSITION = 410u,
            GET_MESSAGE_INTERVAL = 510u,
            IMAGE_START_CAPTURE = 2000u,
            IMAGE_STOP_CAPTURE = 2001u,
            LOGGING_START = 2510u,
            LOGGING_STOP = 2511u,
            MISSION_START = 300u,
            NAV_WAYPOINT = 16u,
            NAV_LOITER_UNLIM = 17u,
            NAV_LOITER_TURNS = 18u,
            NAV_LOITER_TIME = 19u,
            NAV_RETURN_TO_LAUNCH = 20u,
            NAV_LAND = 21u,
            NAV_TAKEOFF = 22u,
            NAV_LAND_LOCAL = 23u,
            NAV_TAKEOFF_LOCAL = 24u,
            NAV_FOLLOW = 25u,
            NAV_CONTINUE_AND_CHANGE_ALT = 30u,
            NAV_LOITER_TO_ALT = 31u,
            NAV_PATHPLANNING = 81u,
            NAV_SPLINE_WAYPOINT = 82u,
            NAV_VTOL_TAKEOFF = 84u,
            NAV_VTOL_LAND = 85u,
            NAV_GUIDED_ENABLE = 92u,
            NAV_DELAY = 93u,
            NAV_PAYLOAD_PLACE = 94u,
            NAV_LAST = 95u,
            NAV_SET_YAW_SPEED = 213u,
            NAV_FENCE_RETURN_POINT = 5000u,
            NAV_FENCE_POLYGON_VERTEX_INCLUSION = 5001u,
            NAV_FENCE_POLYGON_VERTEX_EXCLUSION = 5002u,
            NAV_FENCE_CIRCLE_INCLUSION = 5003u,
            NAV_FENCE_CIRCLE_EXCLUSION = 5004u,
            NAV_RALLY_POINT = 5100u,
            OVERRIDE_GOTO = 252u,
            PANORAMA_CREATE = 2800u,
            PAYLOAD_PREPARE_DEPLOY = 30001u,
            PAYLOAD_CONTROL_DEPLOY = 30002u,
            PREFLIGHT_CALIBRATION = 241u,
            PREFLIGHT_SET_SENSOR_OFFSETS = 242u,
            PREFLIGHT_UAVCAN = 243u,
            PREFLIGHT_STORAGE = 245u,
            PREFLIGHT_REBOOT_SHUTDOWN = 246u,
            REQUEST_PROTOCOL_VERSION = 519u,
            REQUEST_AUTOPILOT_CAPABILITIES = 520u,
            REQUEST_CAMERA_INFORMATION = 521u,
            REQUEST_CAMERA_SETTINGS = 522u,
            REQUEST_STORAGE_INFORMATION = 525u,
            REQUEST_CAMERA_CAPTURE_STATUS = 527u,
            REQUEST_FLIGHT_INFORMATION = 528u,
            REQUEST_CAMERA_IMAGE_CAPTURE = 2002u,
            REQUEST_VIDEO_STREAM_INFORMATION = 2504u,
            RESET_CAMERA_SETTINGS = 529u,
            SET_MESSAGE_INTERVAL = 511u,
            SET_CAMERA_MODE = 530u,
            SET_GUIDED_SUBMODE_STANDARD = 4000u,
            SET_GUIDED_SUBMODE_CIRCLE = 4001u,
            START_RX_PAIR = 500u,
            STORAGE_FORMAT = 526u,
            UAVCAN_GET_NODE_INFO = 5200u,
            VIDEO_START_CAPTURE = 2500u,
            VIDEO_STOP_CAPTURE = 2501u,
            VIDEO_START_STREAMING = 2502u,
            VIDEO_STOP_STREAMING = 2503u,
        };
    }
}

